### ISSUE TITLE
shouldnt this be a .workflow file?

### ISSUE THREAD

**Issue by jtoy** [rtoshiro/alfred-workflows-addcalendarevent#12]
the readme doesnt explain how to install this.

**Comment by zwpaper** [comment]
.workflow file can be found in release
https://github.com/rtoshiro/alfred-workflows-addcalendarevent/releases

**Comment by rtoshiro** [comment]
Hi @jtoy 
Sorry for the delay.
Usually, you just need to double-click on workflow file.
