### ISSUE TITLE
Access to calendar issue

### ISSUE THREAD

**Issue by ludovicvue** [rtoshiro/alfred-workflows-addcalendarevent#13]
Hello @rtoshiro thank you for the workflow!
I have trouble running it though as the window 'give Alfred access to calendar' keeps popping when I try to create an event and wouldn't let me create one (doesn't shut when I click 'give access').

Have you experienced this before ?

**Comment by rtoshiro** [comment]
Hi @ludovicvue 
Well, I haven't any trouble about this but i dont remember if I had to give permission. 
I checked my Privacy settings and yes, I have Alfred 3 in my calendar permission. Can you check if you have Alfred in your permissions as well?
System Settings -> Security & Privacy -> Privacy Tab -> Calendars
Alfred 3 should be there :) If not, you can add manually :)

**Comment by ludovicvue** [comment]
Hi @rtoshiro thanks for your answer, I do have the access granted in my privacy settings but it keep asking anyway, just realize it does the same with 'contacts' so it might be an issue with my version of Alfred. Thanks anyway!
