### ISSUE TITLE
Stop calendar from opening

### ISSUE THREAD

**Issue by ymolodtsov** [rtoshiro/alfred-workflows-addcalendarevent#14]
Hi there!

I really love the workflow and tweaked some of the things to better fit my habits. The only issue I have is every time I add an event it opens the Calendar app itself, which I don't actually need. Is there any way to remove that behaviour? If you can point it out, I'd gladly do that for myself.

Thank you!

**Comment by rtoshiro** [comment]
Yeah i know it is annoying for me as well. But that's how Applescript deal with it. I'm not sure if it is possible to add a calendar event via Applescript without this behavior :/
