### ISSUE TITLE
Ability to specify 'To' time or length of entry

### ISSUE THREAD

**Issue by mishtershmart** [rtoshiro/alfred-workflows-addcalendarevent#2]
As per the title, the ability to specify a 'To' time or a duration for an entry would be ace.

**Comment by caprice-j** [comment]
I vote for "cal Test at 11 pm on mon dur 3 h".
I'd like to add my event like "cal Test at 11 pm on mon dur 10 m".
If I can set the default duration, it's pretty good.

**Comment by rtoshiro** [comment]
Hi
I have released a new version 1.10 with "dur" parameter.
- cal event at 11 on tue dur 10 h
- cal event at 11 on tue dur 4 days
...
Thank you guys for the patience.
Best.

**Comment by mishtershmart** [comment]
Awesome stuff. Tested and working. My only suggestion would be to drop in support for decimal durations at some point. i.e. 3.5 h, 2.25 h, 4.5 days.
