### ISSUE TITLE
Add link to github from readme

### ISSUE THREAD

**Issue by kbrock** [rtoshiro/alfred-workflows-addcalendarevent#5]
I installed and am testing this out. It is looking nice

- Could you add a link in the README file to here?
- Could you also find a way to include the version number? (a VERSION file may be the easiest)

This way, when I come back to this in the future and try and remember these details, I'll be able to quickly find out.

--Keenan

**Comment by rtoshiro** [comment]
Hi Keenan
This workflow already has an README with link and version number ;)
Did you download the latest version? (v 1.10)
If you go to Alfred workflow list, and double-click Add Calendar Event, you can see the readme ;)

Thank you.
Best

**Comment by kbrock** [comment]
Aah, I opened the folder and looked in that readme. See it. Perfect.

Not working for me right now... I'll track it down and report back.

Thanks for this great script.
