### ISSUE TITLE
no instructions how to use

### ISSUE THREAD

**Issue by Morriz** [rtoshiro/alfred-workflows-addcalendarevent#6]
Could you please treat us like dumb f**ks and tell us how to use your repo?

**Comment by piggyslasher** [comment]
^ what he said. I managed to install it but I want to add to Google Calendar. I have it working in the calendar app. But my main calendar is named 'darkbrown@darkbrownandyellow.com' and i cant seem to make that work.

**Comment by rtoshiro** [comment]
@Morriz I really did not understand your question. It's a Workflow for Alfred 2. Just double click on https://github.com/rtoshiro/alfred-workflows-addcalendarevent/releases/download/1.11/Add.Calendar.Event_v.1.11.alfredworkflow file
After that, you follow the examples to interact with. 
Hope it helps.

@piggyslasher I have uploaded a new version of this workflow. I've tested with a calendar name "temp@temp.com" and It works. 
Could you make a try?
Thx!
Best
