### ISSUE TITLE
request to get this working on alfred 3 + El Capitan

### ISSUE THREAD

**Issue by roelleor** [rtoshiro/alfred-workflows-addcalendarevent#7]
This workflow seems awesome! However, when trying it on alfred 3 + El Capitan I get the following error:
[2016-06-22 12:59:45][ERROR: input.scriptfilter] Code 1: result.rb:251:in `parse_cal': undefined method `index' for nil:NilClass (NoMethodError)
	from result.rb:367:in `<main>'

I would be very grateful if I could get this to work on my machine. Cheers!

**Comment by rtoshiro** [comment]
@roelleor 
Thank you. Yes, that workflow I use almost everyday to remind things :)
What command did you type in Alfred console?

**Comment by rtoshiro** [comment]
@roelleor  
Oh, I have found the problem :) It should only affect the result list and not the final commando (when you press Enter). Thank you. I'm going to fix that

**Comment by roelleor** [comment]
superb!

**Comment by rtoshiro** [comment]
@roelleor 
I have released a new version 1.2.1.
Thank you.
Best

**Comment by roelleor** [comment]
Unfortunatelly it doesn’t work on alfred 3, because because of the directory problem (alfred-2 instead of alfred-3):
I have no clue if this directory can be retrieved by code somehow, otherwise it is perhaps possible to have another major release for the alfred 3 version.
[2016-06-23 09:19:21][ERROR: action.script] mainnew.scpt: execution error: mkdir: /Users/[user]/Library/Caches/com.runningwithcrayons.Alfred-2/Workflow Data: No such file or directory (1)

**Comment by rtoshiro** [comment]
Oh. In fact, that is because it uses an library to manage all files. Thank you. I'll fix that.

**Comment by rtoshiro** [comment]
I have just released a new version. I hope it works now ;) 
Thank you.

**Comment by roelleor** [comment]
It works now! Fantastic workflow, thanks!

**Comment by rtoshiro** [comment]
Nice. Thank you.
