### ISSUE TITLE
feature request 1: set default duration to 1 hour, 2) possibility to set to

### ISSUE THREAD

**Issue by roelleor** [rtoshiro/alfred-workflows-addcalendarevent#8]
Hi again! Not really important, but perhaps easy to implement.
1) When adding a calendar event manually, the default duration is 1 hour. Setting it from the workflow the default duration is 2 hours for some reason, which I find rather long (and arbitrary).

2) When adding a calendar event through create quick event it is possible to set the to time, which I think is a really nice feature.
[name] at [x] to [y]

**Comment by rtoshiro** [comment]
Hi @roelleor 
1) Well, you are right. I don't really remember why I put 2 hours as default duration :) I'll try to fix that.
2) Instead you write [x] to [y], you can use the "dur" command, that means "duration" ;)
Following the order: at - on - dur - every - in - @ - alarm
Like that:
```
cal meet my buddy at 10 on mon **dur** 2 hours
```
Best

**Comment by roelleor** [comment]
dur works perfectly! I thought I tried that already, but apparently I did something wrong. Thanks!

**Comment by rtoshiro** [comment]
Thank you!
